<?php

namespace Modules\ObjectBundle\Repository;
use BaseClasses\BaseRepository;
use Modules\ObjectBundle\Entity\File;

/**
 * FileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @method File getById($id)
 */
class FileRepository extends BaseRepository
{
}
