Modules\BucketBundle\Entity\Bucket:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [title]
            errorPath: title
            message: 'This name is already in use'
    properties:
        title:
            - Validator\Constraints\NotNull: ~
            - Length:
                min: 5
                max: 50
                minMessage: 'Your first name must be at least {{ limit }} characters long'
                maxMessage: 'Your first name cannot be longer than {{ limit }} characters'