# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: bcrypt
        Modules\AuthServiceBundle\Security\ServiceUser: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory: { memory: ~ }

    firewalls:
        auth_login:
            host:   api.%app.domain%
            pattern:    ^/v1/login
            security:   false

        api:
            host:   api.%app.domain%
            anonymous: ~
            logout: ~
            guard:
                authenticators:
                    - api.token_authenticator

        docs:
            host:      docs.%app.domain%
            pattern:    ^/
            security:   false

        # disables authentication for assets and the profiler, adapt it according to your needs
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
