# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
#    _defaults:
#        # automatically injects dependencies in your services
#        autowire: true
#        # automatically registers your services as commands, event subscribers, etc.
#        autoconfigure: true
#        # this means you cannot fetch services directly from the container via $container->get()
#        # if you need to do this, you can override this setting on individual services
#        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services

    # add more services, or override services that need manual wiring
    # AppBundle\Service\ExampleService:
    #     arguments:
    #         $someArgument: 'some_value'

    base_entity_manager:
         public: false
         class: BaseClasses\BaseEntityManager
         arguments: ["@base_entity_manager.inner"]

    listener.check.server.upgrade:
         class: BaseClasses\CheckServerUpgrade
         public: true
         arguments: [ "@service_container" ]
         tags:
           - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100 }

    listener.check.server.app_token:
         class: BaseClasses\CheckAppToken
         public: true
         tags:
           - { name: kernel.event_listener, event: kernel.request, method: checkToken, priority: 90 }

    json_exception_listener:
         class: BaseExceptions\ApiExceptionListener
         public: true
         tags:
           - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 100 }

    custom_serializer:
         class: Serializer\Serializer
         public: true

    current_user:
         class: Services\User\CurrentUser
         public: true