<?php

namespace Modules\BucketBundle\Repository;

use BaseClasses\BaseRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Modules\BucketBundle\Entity\Bucket;

/**
 * BucketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @method Bucket getById($id)
 */
class BucketRepository extends BaseRepository
{
    /**
     * @param $userId
     * @return ArrayCollection
     */
    public function getListByProfileId($profileId)
    {
        $query = $this->createQueryBuilder('t');
        $query->select('t')
            ->where('t.profile = :profileId')
            ->setParameter('profileId', $profileId)
            ->getQuery();

        return $this->getCollectionResult($query->getQuery()->getResult());
    }
}
