<?php

namespace Modules\AuthBundle\Repository;

use BaseClasses\BaseRepository;
use Modules\AuthBundle\Entity\AppToken;

/**
 * AppTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @method AppToken getById($id)
 */
class AppTokenRepository extends BaseRepository
{
    /**
     * @param $token
     * @return AppToken
     */
    public function getByToken($token)
    {
        $query = $this->createQueryBuilder('t')
            ->select()
            ->where('t.token = :token')
            ->setParameter('token', $token)
            ->getQuery();

        return $query->getOneOrNullResult();
    }
}
