<?php

namespace Modules\AuthBundle\Repository;

use BaseClasses\BaseRepository;
use Modules\AuthBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @method User getById($id)
 */
class UserRepository extends BaseRepository
{
    /**
     * @param $userName
     * @return User
     */
    public function getByUserName($userName)
    {
        $query = $this->createQueryBuilder('t')
            ->select()
            ->where('t.username = :username')
            ->setParameter('username', $userName)
            ->getQuery();

        return $query->getOneOrNullResult();
    }

    /**\
     * @param $token
     * @return User
     */
    public function getByToken($token)
    {
        $query = $this->createQueryBuilder('t')
            ->select()
            ->innerJoin('Modules\AuthBundle\Entity\UserToken', 'token', 'WITH', 't.id = token.user')
            ->where('token.token = :token')
            ->setParameter('token', $token)
            ->getQuery();

        return $query->getOneOrNullResult();
    }
}
