<?php

namespace Modules\AuthBundle\Repository;

use BaseClasses\BaseRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Modules\AuthBundle\Entity\UserToken;

/**
 * UserTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @method UserToken getById($id)
 */
class UserTokenRepository extends BaseRepository
{
    /**
     * @param $userId
     * @param $authCode
     * @return UserToken
     */
    public function getByUserAndCode($userId, $authCode)
    {
        $query = $this->createQueryBuilder('t')
            ->select()
            ->where('t.user = :user')
            ->andWhere('t.authCode = :authCode')
            ->setParameter('user', $userId)
            ->setParameter('authCode', $authCode)
            ->getQuery();

        return $query->getOneOrNullResult();
    }

    /**
     * @param $token
     * @return UserToken
     */
    public function getByToken($token)
    {
        $query = $this->createQueryBuilder('t')
            ->select()
            ->where('t.token = :token')
            ->setParameter('token', $token)
            ->getQuery();

        return $query->getOneOrNullResult();
    }

    /**
     * @param $userId
     * @return ArrayCollection
     */
    public function getListByUserId($userId)
    {
        $query = $this->createQueryBuilder('t')
            ->select()
            ->where('t.user = :user')
            ->andWhere('t.activation = true')
            ->setParameter('user', $userId)
            ->getQuery();

        return $this->getCollectionResult($query->getResult());
    }
}
