<?php

namespace Modules\AuthBundle\Repository;

use BaseClasses\BaseRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Helpers\DateTimeHelper;
use Modules\AuthBundle\Entity\UserProfile;
use Modules\GeoCatalogBundle\Entity\City;

/**
 * UserProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @method UserProfile getById($id)
 */
class UserProfileRepository extends BaseRepository
{
    /**
     * @param $userId
     * @return UserProfile
     */
    public function getByUserId($userId)
    {
        $query = $this->createQueryBuilder('t')
            ->select('t')
            ->where('t.user = :userId')
            ->setParameter('userId', $userId)
            ->getQuery();

        return $query->getOneOrNullResult();
    }
}
